const GET_PROCESSES_REQUEST = 'GET_PROCESSES_REQUEST';
const GET_PROCESSES_FAILURE = 'GET_PROCESSES_FAILURE';
const GET_PROCESSES_SUCCESS = 'GET_PROCESSES_SUCCESS';
const CLEAR_CHOOSE_PROCESSES_ERROR_MESSAGE = "CLEAR_CHOOSE_PROCESSES_ERROR_MESSAGE";
const CLOSE_CHOOSE_PROCESSES_MODAL = "CLOSE_CHOOSE_PROCESSES_MODAL";

export {
    GET_PROCESSES_REQUEST,
    GET_PROCESSES_FAILURE,
    GET_PROCESSES_SUCCESS,
    CLEAR_CHOOSE_PROCESSES_ERROR_MESSAGE,
    CLOSE_CHOOSE_PROCESSES_MODAL
};
