const CREATE_PROCESS_REQUEST = 'CREATE_PROCESS_REQUEST';
const CREATE_PROCESS_FAILURE = 'CREATE_PROCESS_FAILURE';
const CREATE_PROCESS_SUCCESS = 'CREATE_PROCESS_SUCCESS';
const GET_START_EVENT_XML_SUCCESS = 'GET_START_EVENT_XML_SUCCESS';
const CLEAR_CREATE_ERROR_MESSAGE = "CLEAR_CREATE_ERROR_MESSAGE";
const CREATE_PROCESS_UPDATE_STATE = "CREATE_PROCESS_UPDATE_STATE";

export {
    CREATE_PROCESS_REQUEST,
    CREATE_PROCESS_FAILURE,
    CREATE_PROCESS_SUCCESS,
    CLEAR_CREATE_ERROR_MESSAGE,
    CREATE_PROCESS_UPDATE_STATE,
    GET_START_EVENT_XML_SUCCESS
};
