const GET_TASKLIST_REQUEST = 'GET_TASKLIST_REQUEST';
const GET_TASKLIST_FAILURE = 'GET_TASKLIST_FAILURE';
const GET_TASKSDATA_SUCCESS = 'GET_TASKSDATA_SUCCESS';
const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS';
const DELETE_TASK = 'DELETE_TASK';
const SET_CURRENT_ITEMS_PART = 'SET_CURRENT_ITEMS_PART';

export { GET_TASKLIST_REQUEST, GET_TASKLIST_FAILURE, GET_TASKSDATA_SUCCESS, CREATE_TASK_SUCCESS, DELETE_TASK, SET_CURRENT_ITEMS_PART };
